name: os-test

on:
  push:
    branches:
      - main


jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Linux tests
        run: echo "Runnning tests on Linux"

  windows-test:
    runs-on: windows-latest
    steps:
     - name: Windows tests
       run: echo "Running tests on Windows"
